### ISSUE TITLE
[bug] culring a nodejs function produces: "TypeError: Cannot read property 'info' of undefined"

### ISSUE THREAD

**Issue by alanfx** [boson-project/functions#22]
**Describe the bug**
Created a nodejs function, ran it locally, and curling the loclhost:8080 endpoint produces an error.

**To Reproduce**
1. `kn faas init -l node`
1. `npm run local`
1. `curl -X POST -d '{"hello": "world"}'  -H'Content-type: application/json'  -H'Ce-id: 1' -H'Ce-source: cloud-event-example' -H'Ce-type: dev.knative.example' -H'Ce-specversion: 1.0' http://localhost:8080`

Result: `{"statusMessage":"Cannot read property 'info' of undefined"}`
```
TypeError: Cannot read property 'info' of undefined
    at invoke (/home/afield/Development/go/bin/func1/index.js:30:15)
    at invokeFunction (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/lib/invoker.js:21:34)
    at Object.doPost (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/lib/request-handler.js:18:28)
    at preHandlerCallback (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/node_modules/fastify/lib/handleRequest.js:124:28)
    at next (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/node_modules/fastify/lib/hooks.js:158:7)
    at Object.<anonymous> (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/lib/event-handler.js:26:5)
    at hookIterator (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/node_modules/fastify/lib/hooks.js:221:10)
    at next (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/node_modules/fastify/lib/hooks.js:162:20)
    at Object.<anonymous> (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/index.js:32:5)
    at hookIterator (/home/afield/.npm/_npx/1178569/lib/node_modules/faas-js-runtime/node_modules/fastify/lib/hooks.js:221:10)
```

**Expected behavior**
The CloudEvent is delivered to the function without error.

**Comment by matejvasek** [comment]
@alanfx Thanks for the feedback!
I think that when using CloudEvents the function should be initialized by `kn faas init -l node -t events`.
Otherwise plain `HTTP` is assumed. With plain `HTTP` the function signature is different.

**Comment by matejvasek** [comment]
When the runtime receives CE it expects that the user function accepts two parameters, but `HTTP` template has only one.

**Comment by matejvasek** [comment]
@lance Maybe it would be better to pass CloudEvent as second parameter, not the first.

Also if it's possible in JS, the runtime could check function arity and return `Bad request` if signature doesn't match.

**Comment by matejvasek** [comment]
@lance I mean something like this. Beware I didn't try to run code below.
```diff
diff --git a/lib/invoker.js b/lib/invoker.js
index ef8f83a..3ab2d15 100644
--- a/lib/invoker.js
+++ b/lib/invoker.js
@@ -18,11 +18,25 @@ module.exports = function invoker(func) {
       if (context.cloudevent && context.cloudevent.data) {
         // If there is a cloud event, provide the data
         // as the first parameter
-        payload.response = await func(context.cloudevent.data, context);
+        if (func.length === 2) {
+          payload.response = await func(context.cloudevent.data, context);
+        } else {
+          payload.response = {
+            statusCode: 400,
+            statusMessage: 'Received CloudEvent but handler is plain HTTP handler.'
+          };
+        }
       } else {
         // Invoke with context
         // TODO: Should this actually just get the Node.js request object?
-        payload.response = await func(context);
+        if (func.length === 1) {
+          payload.response = await func(context);
+        } else {
+          payload.response = {
+            statusCode: 400,
+            statusMessage: 'Received plain HTTP but handler is CloudEvent handler.'
+          };
+        }
       }
     } catch (err) {
       log.error(err);
```

**Comment by alanfx** [comment]
@matejvasek you are exactly right! I was confused by the output of the `npm run local` command:

```
go/bin/func1 is 📦 v0.1.0 via ⬢ v12.19.0 on ☁️  us-west-1 took 15s 
❯ npm run local

> http-handler@0.1.0 local /home/afield/Development/go/bin/func1
> npx faas-js-runtime ./index.js

{"level":30,"time":1603999818473,"pid":1189464,"hostname":"afield-lenovo","msg":"Server listening at http://0.0.0.0:8080"}

The server has started.

You can use curl to POST an event to the endpoint:

curl -X POST -d '{"hello": "world"}' \
    -H'Content-type: application/json' \
    -H'Ce-id: 1' \
    -H'Ce-source: cloud-event-example' \
    -H'Ce-type: dev.knative.example' \
    -H'Ce-specversion: 1.0' \
    http://localhost:8080
```

Maybe the text should also mention that `curl http://localhost:8080` will work for HTTP endpoints?
